# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeBts < Formula
  desc "Verify before you code — catches spec errors before they become debugging sessions"
  homepage "https://github.com/imtemp-dev/claude-bts"
  version "0.3.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/imtemp-dev/claude-bts/releases/download/v0.3.14/claude-bts_0.3.14_darwin_amd64.tar.gz"
      sha256 "c85f5dbae6ef1925ea8435ecbd786b0cdfe62915a8fa91c95b48fa732b5dc22a"

      define_method(:install) do
        bin.install "bts"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/imtemp-dev/claude-bts/releases/download/v0.3.14/claude-bts_0.3.14_darwin_arm64.tar.gz"
      sha256 "efdf64da17d4b19c985e84d424ab3517986e703e92d8396c8b3754d7a5c084c4"

      define_method(:install) do
        bin.install "bts"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/imtemp-dev/claude-bts/releases/download/v0.3.14/claude-bts_0.3.14_linux_amd64.tar.gz"
      sha256 "a11c8dd1b6d732f95d015cbc860de281addfa0e954e614a1e80138d17b89adc5"
      define_method(:install) do
        bin.install "bts"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/imtemp-dev/claude-bts/releases/download/v0.3.14/claude-bts_0.3.14_linux_arm64.tar.gz"
      sha256 "b1607ff58524887d0e0aedde87cf897ebd3c5db9ffba0585cd4693e3b7d7187e"
      define_method(:install) do
        bin.install "bts"
      end
    end
  end

  test do
    system "#{bin}/bts", "--version"
  end
end
