# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeForge < Formula
  desc "Document-first AI development — iterate on specs, not code"
  homepage "https://github.com/imtemp-dev/claude-forge"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/imtemp-dev/claude-forge/releases/download/v0.2.0/claude-forge_0.2.0_darwin_amd64.tar.gz"
      sha256 "8476a52b08aed5698f760c30b8293c4925fb5c2536f1bf026e528e4833dad221"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/imtemp-dev/claude-forge/releases/download/v0.2.0/claude-forge_0.2.0_darwin_arm64.tar.gz"
      sha256 "2bf9818448f59e5d0b49688d16b7ccd2d6e282d1133884514922e06414f5f6b3"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/imtemp-dev/claude-forge/releases/download/v0.2.0/claude-forge_0.2.0_linux_amd64.tar.gz"
      sha256 "8dcc31ead8d370f1f1f22b699f89ba0738f00f69e3cff7fcf029fd7ef3a64095"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/imtemp-dev/claude-forge/releases/download/v0.2.0/claude-forge_0.2.0_linux_arm64.tar.gz"
      sha256 "09f02ed378243d27ae7c2861949dfe2e4d0a331354763cf8f0c0456a42003967"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "--version"
  end
end
